/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualizationRouteImport } from './routes/visualization'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ImportsRouteImport } from './routes/imports'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as TemplatesMachineRouteImport } from './routes/templates.$machine'

const VisualizationRoute = VisualizationRouteImport.update({
  id: '/visualization',
  path: '/visualization',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsRoute = ImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesMachineRoute = TemplatesMachineRouteImport.update({
  id: '/$machine',
  path: '/$machine',
  getParentRoute: () => TemplatesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/imports': typeof ImportsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/visualization': typeof VisualizationRoute
  '/templates/$machine': typeof TemplatesMachineRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/imports': typeof ImportsRoute
  '/visualization': typeof VisualizationRoute
  '/templates/$machine': typeof TemplatesMachineRoute
  '/templates': typeof TemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/imports': typeof ImportsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/visualization': typeof VisualizationRoute
  '/templates/$machine': typeof TemplatesMachineRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/imports'
    | '/templates'
    | '/visualization'
    | '/templates/$machine'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/imports' | '/visualization' | '/templates/$machine' | '/templates'
  id:
    | '__root__'
    | '/'
    | '/imports'
    | '/templates'
    | '/visualization'
    | '/templates/$machine'
    | '/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportsRoute: typeof ImportsRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  VisualizationRoute: typeof VisualizationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visualization': {
      id: '/visualization'
      path: '/visualization'
      fullPath: '/visualization'
      preLoaderRoute: typeof VisualizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports': {
      id: '/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/$machine': {
      id: '/templates/$machine'
      path: '/$machine'
      fullPath: '/templates/$machine'
      preLoaderRoute: typeof TemplatesMachineRouteImport
      parentRoute: typeof TemplatesRoute
    }
  }
}

interface TemplatesRouteChildren {
  TemplatesMachineRoute: typeof TemplatesMachineRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesMachineRoute: TemplatesMachineRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportsRoute: ImportsRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  VisualizationRoute: VisualizationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
